/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package javaswingdev.chart;

import java.sql.*;
import config.DatabaseConfig;
import java.awt.Color;
import config.ModelDataPemasukan;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author MI TA
 */
public class ChartPemasukan extends javax.swing.JPanel {

    Connection connection = DatabaseConfig.getConnection();

    /**
     * Creates new form ChartPemasukan
     */
    public ChartPemasukan() {
        initComponents();
        chart.setTitle("Pemasukan");
        chart.addLegend(" ", Color.decode("#00ff87"), Color.decode("#60efff"));
//        chart.addLegend("Pengeluaran", Color.decode("#57ebde"), Color.decode("#aefb2a"));
        setData();
    }

    private void setData() {
        try {
            String[] bln = {"Dec", "Nov", "Oct", "Sep", "Aug", "Jul", "Jun", "May", "Apr", "Mar", "Feb", "Jan"};
            double[] ttl = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
            List<ModelDataPemasukan> list = new ArrayList<>();
            String query = "SELECT * FROM v_pemasukan LIMIT 12";
            PreparedStatement p = connection.prepareStatement(query);
            ResultSet rs = p.executeQuery();
            while (rs.next()) {
//                int index=0;
                String bulan = rs.getString("bulan");
                double pemasukan = rs.getDouble("pemasukan");
                for (int i = 0; i < bln.length; i++) {
                    if (bln[i].equals(bulan)) {
                        ttl[i] = pemasukan;
                    }
                }
            }
            for (int i = 0; i < bln.length; i++) {
                list.add(new ModelDataPemasukan(bln[i], ttl[i]));

            }
            rs.close();
            p.close();

            for (int i = list.size() - 1; i >= 0; i--) {
                ModelDataPemasukan d = list.get(i);
                chart.addData(new ModelChart(d.getBulan(), new double[]{d.getPemasukkan()}));
            }
            chart.start();
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chart = new javaswingdev.chart.CurveLineChart();

        setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chart, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chart, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javaswingdev.chart.CurveLineChart chart;
    // End of variables declaration//GEN-END:variables
}
