/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package javaswingdev.form;

import config.DatabaseConfig;
import java.sql.*;
import java.util.Locale;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import raven.alerts.MessageAlerts;
import java.text.NumberFormat;

/**
 *
 * @author rayag
 */
public class Form_Pengeluaran extends javax.swing.JPanel {

    DefaultTableModel tableModel;
    Connection connection = null;
    String kodeTerpilih = "";
    int aksi = 0;
    Locale localeID = new Locale("in", "ID");
    NumberFormat formatRupiah = NumberFormat.getCurrencyInstance(localeID);

    public Form_Pengeluaran() {
        getCon();
        String[] judul = {"Kode Pengeluaran", "Nama", "keterangan", "Jumlah", "Total Harga", "Tanggal Pengeluaran"};
        tableModel = new DefaultTableModel(judul, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        loadDataPengeluaran("");

        initComponents();
        tbl_pengeluaran.setModel(tableModel);
    }

    private void getCon() {
        try {
            connection = DatabaseConfig.getConnection();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void enabledButton(int cc) {
        if (cc == 1) {
            addBtn.setEnabled(true);
        }
    }

    public void disabledButton() {
        addBtn.setEnabled(true);

    }

    protected void popupHandler(String popupMsg, int status) {
        addBtn.setEnabled(true);
        if (status == 1) {
            MessageAlerts.getInstance().showMessage("SUCCESS", popupMsg, MessageAlerts.MessageType.SUCCESS);
        } else {
            MessageAlerts.getInstance().showMessage("ERROR", popupMsg, MessageAlerts.MessageType.ERROR);
        }
        aksi = 0;
    }

    protected void loadDataPengeluaran(String cari) {
        if (connection != null) {
            try {
                String query = "SELECT kode_pengeluaran, user.nama,  tnggl_pengeluaran, keterangan, jumlah, harga"
                        + " FROM pengeluaran"
                        + " LEFT JOIN user ON user.id=pengeluaran.id_user"
                        + " LEFT JOIN bahanbaku ON bahanbaku.kode_bahanbaku=pengeluaran.kode_bahanbaku"
                        + " WHERE keterangan LIKE ?";
                PreparedStatement st = connection.prepareStatement(query);
                st.setString(1, "%" + cari + "%");
                ResultSet rs = st.executeQuery();
                tableModel.setRowCount(0);
                while (rs.next()) {
                    String[] data = {rs.getString(1), rs.getString(2), rs.getString(4), rs.getString(5), formatRupiah.format(rs.getDouble(6)), rs.getString(3)};
                    tableModel.addRow(data);
                }
                rs.close();
                st.close();
            } catch (Exception e) {
                e.printStackTrace();
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container1 = new javaswingdev.util.Container();
        jLabel1 = new javax.swing.JLabel();
        search = new javaswingdev.util.TextFieldSearchOption();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_pengeluaran = new javax.swing.JTable();
        addBtn = new javaswingdev.util.Button();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PENGELUARAN");

        search.setColorOverlay1(new java.awt.Color(255, 225, 55));
        search.setColorOverlay2(new java.awt.Color(0, 220, 0));
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });

        tbl_pengeluaran.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbl_pengeluaran.setModel(tableModel);
        tbl_pengeluaran.setRowHeight(30);
        tbl_pengeluaran.getTableHeader().setReorderingAllowed(false);
        tbl_pengeluaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_pengeluaranMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_pengeluaran);

        addBtn.setText("TAMBAH");
        addBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout container1Layout = new javax.swing.GroupLayout(container1);
        container1.setLayout(container1Layout);
        container1Layout.setHorizontalGroup(
            container1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(container1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(container1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(container1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1)
                        .addGroup(container1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 447, Short.MAX_VALUE)
                            .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30))
        );
        container1Layout.setVerticalGroup(
            container1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(container1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(container1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(50, 50, 50)
                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(container1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        tambahPengeluaran tpengeluaran = new tambahPengeluaran(this, null);
        tpengeluaran.setVisible(true);
        tpengeluaran.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        aksi = 1;
    }//GEN-LAST:event_addBtnActionPerformed

    private void tbl_pengeluaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_pengeluaranMouseClicked
        int selectedRow = tbl_pengeluaran.getSelectedRow();
        if (aksi == 0) {
            if (selectedRow != -1 && selectedRow < tbl_pengeluaran.getRowCount()) {
                kodeTerpilih = (String) tableModel.getValueAt(selectedRow, 0);
            }
        }
    }//GEN-LAST:event_tbl_pengeluaranMouseClicked

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
        loadDataPengeluaran(search.getText());
    }//GEN-LAST:event_searchKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javaswingdev.util.Button addBtn;
    private javaswingdev.util.Container container1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javaswingdev.util.TextFieldSearchOption search;
    private javax.swing.JTable tbl_pengeluaran;
    // End of variables declaration//GEN-END:variables
}
